//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:2.0.50727.3082
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Languages {
    
    
    public class Current {
        
        private static ILanguage _Language;
        
        private Current() {
        }
        
        /// <summary>
        ///  Call GetLanguages() to retrieve a list of possible languages that can be used to set this property.
        ///  The default value is the default language.
        /// </summary>
        public static ILanguage Language {
            get {
                if ((_Language == null)) {
                    System.Collections.Generic.List<ILanguage> list = Current.GetLanguages();
                    for (int i = 0; (i < list.Count); i = (i + 1)) {
                        if (list[i].IsDefault) {
                            _Language = list[i];
                            return _Language;
                        }
                    }
                }
                return _Language;
            }
            set {
                _Language = value;
            }
        }
        
        /// <summary>
        ///  Gets a list of available languages defined in this assembly.
        /// </summary>
        public static System.Collections.Generic.List<ILanguage> GetLanguages() {
            System.Collections.Generic.List<ILanguage> items = new System.Collections.Generic.List<ILanguage>();
            System.Type[] exportedTypes = System.Reflection.Assembly.GetExecutingAssembly().GetExportedTypes();
            for (int i = 0; (i < exportedTypes.Length); i = (i + 1)) {
                if (exportedTypes[i].IsClass) {
                    if ((exportedTypes[i].GetInterface("ILanguage") != null)) {
                        try {
                            object obj = System.Activator.CreateInstance(exportedTypes[i]);
                            ILanguage interfaceReference = ((ILanguage)(obj));
                            if ((interfaceReference != null)) {
                                items.Add(interfaceReference);
                            }
                        }
                        catch (System.Exception ) {
                        }
                    }
                }
            }
            return items;
        }
    }
}
