//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:2.0.50727.3082
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Languages {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class English : ILanguage {
        
        private global::System.Resources.ResourceManager resourceMan;
        
        private global::System.Globalization.CultureInfo resourceCulture;
        
        public English() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Languages.English", typeof(English).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public global::System.Globalization.CultureInfo Culture {
            get {
                if (object.ReferenceEquals(resourceCulture, null)) {
                    global::System.Globalization.CultureInfo temp = new global::System.Globalization.CultureInfo("en");
                    resourceCulture = temp;
                }
                return resourceCulture;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ability.
        /// </summary>
        public string ChangeNamingStandard {
            get {
                return ResourceManager.GetString("ChangeNamingStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ability.
        /// </summary>
        public string Ability {
            get {
                return ResourceManager.GetString("Ability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Action Analysis Editor.
        /// </summary>
        public string ActionAnalysisEditor {
            get {
                return ResourceManager.GetString("ActionAnalysisEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Actions Analysis File.
        /// </summary>
        public string ActionsAnalysisFile {
            get {
                return ResourceManager.GetString("ActionsAnalysisFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ada.
        /// </summary>
        public string Ada {
            get {
                return ResourceManager.GetString("Ada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Adaptability of the player.
        /// </summary>
        public string AdaptabilityOfThePlayer {
            get {
                return ResourceManager.GetString("AdaptabilityOfThePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Adaptability values are contained into range 0-20.
        /// </summary>
        public string AdaptabilityValuesAreContainedIntoRange020 {
            get {
                return ResourceManager.GetString("AdaptabilityValuesAreContainedIntoRange020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Age.
        /// </summary>
        public string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Agg.
        /// </summary>
        public string Agg {
            get {
                return ResourceManager.GetString("Agg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Aggressivity.
        /// </summary>
        public string Aggressivity {
            get {
                return ResourceManager.GetString("Aggressivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a All votes from scouts.
        /// </summary>
        public string AllVotesFromScouts {
            get {
                return ResourceManager.GetString("AllVotesFromScouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Analyzed actions, in percentage.
        /// </summary>
        public string AnalyzedActionsInPercentage {
            get {
                return ResourceManager.GetString("AnalyzedActionsInPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Analyze Match.
        /// </summary>
        public string AnalyzeMatch {
            get {
                return ResourceManager.GetString("AnalyzeMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Are you a PRO user? (You can change your status in the Option form).
        /// </summary>
        public string AreYouAPROUserYouCanChangeYourStatusInTheOptionForm {
            get {
                return ResourceManager.GetString("AreYouAPROUserYouCanChangeYourStatusInTheOptionForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Are you sure that you want to remove the match .
        /// </summary>
        public string AreYouSureThatYouWantToRemoveTheMatch {
            get {
                return ResourceManager.GetString("AreYouSureThatYouWantToRemoveTheMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ari.
        /// </summary>
        public string Ari {
            get {
                return ResourceManager.GetString("Ari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ASI to TI Calculator.
        /// </summary>
        public string ASIToTICalculator {
            get {
                return ResourceManager.GetString("ASIToTICalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a A-Team Players.
        /// </summary>
        public string ATeamPlayers {
            get {
                return ResourceManager.GetString("ATeamPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Att.
        /// </summary>
        public string Att {
            get {
                return ResourceManager.GetString("Att", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Average Rating in this season.
        /// </summary>
        public string AverageRatingInThisSeason {
            get {
                return ResourceManager.GetString("AverageRatingInThisSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Average value of TI, in the last weeks.
        /// </summary>
        public string AverageValueOfTIInTheLastWeeks {
            get {
                return ResourceManager.GetString("AverageValueOfTIInTheLastWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Away.
        /// </summary>
        public string Away {
            get {
                return ResourceManager.GetString("Away", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a been sent to Led Lennon that will remove this bug as soon as possible..
        /// </summary>
        public string BeenSentToLedLennonThatWillRemoveThisBugAsSoonAsPossible {
            get {
                return ResourceManager.GetString("BeenSentToLedLennonThatWillRemoveThisBugAsSoonAsPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Best Skills.
        /// </summary>
        public string Best_Skills {
            get {
                return ResourceManager.GetString("Best_Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a BestSkills.
        /// </summary>
        public string BestSkills {
            get {
                return ResourceManager.GetString("BestSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Blooming.
        /// </summary>
        public string Blooming {
            get {
                return ResourceManager.GetString("Blooming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Blooming and Psycology votes.
        /// </summary>
        public string BloomingAndPsycologyVotes {
            get {
                return ResourceManager.GetString("BloomingAndPsycologyVotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Browse.
        /// </summary>
        public string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a B-Team Players.
        /// </summary>
        public string BTeamPlayers {
            get {
                return ResourceManager.GetString("BTeamPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cancel.
        /// </summary>
        public string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Changed Default directory.
        /// </summary>
        public string ChangedDefaultDirectory {
            get {
                return ResourceManager.GetString("ChangedDefaultDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Change Player Properties.
        /// </summary>
        public string ChangePlayerProperties {
            get {
                return ResourceManager.GetString("ChangePlayerProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Clear Decimals.
        /// </summary>
        public string ClearDecimals {
            get {
                return ResourceManager.GetString("ClearDecimals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Com.
        /// </summary>
        public string Com {
            get {
                return ResourceManager.GetString("Com", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Compute Growth.
        /// </summary>
        public string ComputeGrowth {
            get {
                return ResourceManager.GetString("ComputeGrowth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Configured Match Types.
        /// </summary>
        public string ConfiguredMatchTypes {
            get {
                return ResourceManager.GetString("ConfiguredMatchTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a CP.
        /// </summary>
        public string CP {
            get {
                return ResourceManager.GetString("CP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cro.
        /// </summary>
        public string Cro {
            get {
                return ResourceManager.GetString("Cro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cross.
        /// </summary>
        public string Cross {
            get {
                return ResourceManager.GetString("Cross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Crowd.
        /// </summary>
        public string Crowd {
            get {
                return ResourceManager.GetString("Crowd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Dark Green Arrows = .
        /// </summary>
        public string DarkGreenArrows {
            get {
                return ResourceManager.GetString("DarkGreenArrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Dark Red Arrows = .
        /// </summary>
        public string DarkRedArrows {
            get {
                return ResourceManager.GetString("DarkRedArrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Data Directory.
        /// </summary>
        public string DataDirectory {
            get {
                return ResourceManager.GetString("DataDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Data Edit.
        /// </summary>
        public string DataEdit {
            get {
                return ResourceManager.GetString("DataEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Data Item relative to week .
        /// </summary>
        public string DataItemRelativeToWeek {
            get {
                return ResourceManager.GetString("DataItemRelativeToWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Date.
        /// </summary>
        public string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Date Format not valid: .
        /// </summary>
        public string DateFormatNotValid {
            get {
                return ResourceManager.GetString("DateFormatNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Date of the Match.
        /// </summary>
        public string DateOfTheMatch {
            get {
                return ResourceManager.GetString("DateOfTheMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Def.
        /// </summary>
        public string Def {
            get {
                return ResourceManager.GetString("Def", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Default Player Nation.
        /// </summary>
        public string DefaultPlayerNation {
            get {
                return ResourceManager.GetString("DefaultPlayerNation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Delete Data Set.
        /// </summary>
        public string DeleteDataSet {
            get {
                return ResourceManager.GetString("DeleteDataSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Delete match.
        /// </summary>
        public string DeleteMatch {
            get {
                return ResourceManager.GetString("DeleteMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Delete Selected Match.
        /// </summary>
        public string DeleteSelectedMatch {
            get {
                return ResourceManager.GetString("DeleteSelectedMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Deleting old players from database.
        /// </summary>
        public string DeletingOldPlayersFromDatabase {
            get {
                return ResourceManager.GetString("DeletingOldPlayersFromDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Delta Decimals = +.
        /// </summary>
        public string DeltaDecimals {
            get {
                return ResourceManager.GetString("DeltaDecimals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Dev.
        /// </summary>
        public string Dev {
            get {
                return ResourceManager.GetString("Dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Display Statistics For The Training of This Week.
        /// </summary>
        public string DisplayStatisticsForTheTrainingOfThisWeek {
            get {
                return ResourceManager.GetString("DisplayStatisticsForTheTrainingOfThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Do you want to replace the data set that is in the same week?.
        /// </summary>
        public string DoYouWantToReplaceTheDataSetThatIsInTheSameWeek {
            get {
                return ResourceManager.GetString("DoYouWantToReplaceTheDataSetThatIsInTheSameWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Edit.
        /// </summary>
        public string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Edit Gain Set.
        /// </summary>
        public string EditGainSet {
            get {
                return ResourceManager.GetString("EditGainSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error loading a file.
        /// </summary>
        public string ErrorLoadingAFile {
            get {
                return ResourceManager.GetString("ErrorLoadingAFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Evidence Gain on the players table.
        /// </summary>
        public string EvidenceGainOnThePlayersTable {
            get {
                return ResourceManager.GetString("EvidenceGainOnThePlayersTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Evidence Skills for Gains.
        /// </summary>
        public string EvidenceSkillsForGains {
            get {
                return ResourceManager.GetString("EvidenceSkillsForGains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Exit.
        /// </summary>
        public string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Explore Player.
        /// </summary>
        public string ExplorePlayer {
            get {
                return ResourceManager.GetString("ExplorePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Export History To Excel.
        /// </summary>
        public string ExportHistoryToExcel {
            get {
                return ResourceManager.GetString("ExportHistoryToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Export Team to Clipboard in Excel Format.
        /// </summary>
        public string ExportTeamToClipboardInExcelFormat {
            get {
                return ResourceManager.GetString("ExportTeamToClipboardInExcelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Export Training to Clipboard.
        /// </summary>
        public string ExportTrainingToClipboard {
            get {
                return ResourceManager.GetString("ExportTrainingToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Export Training Week to Clipboard in Excel Format.
        /// </summary>
        public string ExportTrainingWeekToClipboardInExcelFormat {
            get {
                return ResourceManager.GetString("ExportTrainingWeekToClipboardInExcelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a External Editors.
        /// </summary>
        public string ExternalEditors {
            get {
                return ResourceManager.GetString("ExternalEditors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a File.
        /// </summary>
        public string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Fill this cells with the phrases that scouts uses to review your players.
        /// </summary>
        public string FillThisCellsWithThePhrasesThatScoutsUsesToReviewYourPlayers {
            get {
                return ResourceManager.GetString("FillThisCellsWithThePhrasesThatScoutsUsesToReviewYourPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Fin.
        /// </summary>
        public string Fin {
            get {
                return ResourceManager.GetString("Fin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Finishing.
        /// </summary>
        public string Finishing {
            get {
                return ResourceManager.GetString("Finishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a First of all, open the Calendar Page of your team using the relative button on the match menu
        ///.
        /// </summary>
        public string FirstOfAllOpenTheCalendarPageOfYourTeamUsingTheRelativeButtonOnTheMatchMenu {
            get {
                return ResourceManager.GetString("FirstOfAllOpenTheCalendarPageOfYourTeamUsingTheRelativeButtonOnTheMatchMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Function.
        /// </summary>
        public string Function {
            get {
                return ResourceManager.GetString("Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gain Set.
        /// </summary>
        public string GainSet {
            get {
                return ResourceManager.GetString("GainSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Generics.
        /// </summary>
        public string Generics {
            get {
                return ResourceManager.GetString("Generics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Get Automatically.
        /// </summary>
        public string GetAutomatically {
            get {
                return ResourceManager.GetString("GetAutomatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a GK.
        /// </summary>
        public string GK {
            get {
                return ResourceManager.GetString("GK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a GK Skill.
        /// </summary>
        public string GKSkill {
            get {
                return ResourceManager.GetString("GKSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a GoalKeeper History.
        /// </summary>
        public string GoalKeeperHistory {
            get {
                return ResourceManager.GetString("GoalKeeperHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a GoalKeepers.
        /// </summary>
        public string GoalKeepers {
            get {
                return ResourceManager.GetString("GoalKeepers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Goals scored.
        /// </summary>
        public string GoalsScored {
            get {
                return ResourceManager.GetString("GoalsScored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Goto Match Report Page.
        /// </summary>
        public string GotoMatchReportPage {
            get {
                return ResourceManager.GetString("GotoMatchReportPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Goto Trainers Page.
        /// </summary>
        public string GotoTrainersPage {
            get {
                return ResourceManager.GetString("GotoTrainersPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Han.
        /// </summary>
        public string Han {
            get {
                return ResourceManager.GetString("Han", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Hea.
        /// </summary>
        public string Hea {
            get {
                return ResourceManager.GetString("Hea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Heading.
        /// </summary>
        public string Heading {
            get {
                return ResourceManager.GetString("Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Help.
        /// </summary>
        public string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Home.
        /// </summary>
        public string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a If the box is checked, the match have been already downloaded.
        /// </summary>
        public string IfTheBoxIsCheckedTheMatchHaveBeenAlreadyDownloaded {
            get {
                return ResourceManager.GetString("IfTheBoxIsCheckedTheMatchHaveBeenAlreadyDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Import Private Players Data.
        /// </summary>
        public string ImportPrivatePlayersData {
            get {
                return ResourceManager.GetString("ImportPrivatePlayersData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Import Training Week From Clipboard in Excel Format.
        /// </summary>
        public string ImportTrainingWeekFromClipboardInExcelFormat {
            get {
                return ResourceManager.GetString("ImportTrainingWeekFromClipboardInExcelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Injuries.
        /// </summary>
        public string Injuries {
            get {
                return ResourceManager.GetString("Injuries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Insert here the information relative to your scouts.
        /// </summary>
        public string InsertHereTheInformationRelativeToYourScouts {
            get {
                return ResourceManager.GetString("InsertHereTheInformationRelativeToYourScouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Installation Directory.
        /// </summary>
        public string InstallationDirectory {
            get {
                return ResourceManager.GetString("InstallationDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a  is not a valid file.
        /// </summary>
        public string IsNotAValidFile {
            get {
                return ResourceManager.GetString("IsNotAValidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a  is not a valid file. 
        ///Exception loading the file: .
        /// </summary>
        public string IsNotAValidFileExceptionLoadingTheFile {
            get {
                return ResourceManager.GetString("IsNotAValidFileExceptionLoadingTheFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Is this file relative to today?.
        /// </summary>
        public string IsThisFileRelativeToToday {
            get {
                return ResourceManager.GetString("IsThisFileRelativeToToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Jum.
        /// </summary>
        public string Jum {
            get {
                return ResourceManager.GetString("Jum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Kic.
        /// </summary>
        public string Kic {
            get {
                return ResourceManager.GetString("Kic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Lea.
        /// </summary>
        public string Lea {
            get {
                return ResourceManager.GetString("Lea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Leadership.
        /// </summary>
        public string Leadership {
            get {
                return ResourceManager.GetString("Leadership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Light Red Arrows = .
        /// </summary>
        public string LightRedArrows {
            get {
                return ResourceManager.GetString("LightRedArrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Load.
        /// </summary>
        public string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Load a squad file first.
        /// </summary>
        public string LoadASquadFileFirst {
            get {
                return ResourceManager.GetString("LoadASquadFileFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Load Calendar as HTML file.
        /// </summary>
        public string LoadCalendarAsHTMLFile {
            get {
                return ResourceManager.GetString("LoadCalendarAsHTMLFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Load from Excel Form.
        /// </summary>
        public string LoadFromExcelForm {
            get {
                return ResourceManager.GetString("LoadFromExcelForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Load HTM Data.
        /// </summary>
        public string LoadHTMData {
            get {
                return ResourceManager.GetString("LoadHTMData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Load Team File as HTML file.
        /// </summary>
        public string ReloadFixturesAndMatches {
            get {
                return ResourceManager.GetString("ReloadFixturesAndMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Load Team File from XML.
        /// </summary>
        public string LoadTeamFileFromXML {
            get {
                return ResourceManager.GetString("LoadTeamFileFromXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Load Training as HTML file.
        /// </summary>
        public string LoadTrainingAsHTMLFile {
            get {
                return ResourceManager.GetString("LoadTrainingAsHTMLFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Load Training Data in Excel Format.
        /// </summary>
        public string LoadTrainingDataInExcelFormat {
            get {
                return ResourceManager.GetString("LoadTrainingDataInExcelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Location.
        /// </summary>
        public string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Lon.
        /// </summary>
        public string Lon {
            get {
                return ResourceManager.GetString("Lon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Longshots.
        /// </summary>
        public string Longshots {
            get {
                return ResourceManager.GetString("Longshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Main.
        /// </summary>
        public string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Main Squad.
        /// </summary>
        public string MainSquad {
            get {
                return ResourceManager.GetString("MainSquad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Mar.
        /// </summary>
        public string Mar {
            get {
                return ResourceManager.GetString("Mar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Marking.
        /// </summary>
        public string Marking {
            get {
                return ResourceManager.GetString("Marking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Matches.
        /// </summary>
        public string Matches {
            get {
                return ResourceManager.GetString("Matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Match Start.
        /// </summary>
        public string MatchStart {
            get {
                return ResourceManager.GetString("MatchStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Match Stats.
        /// </summary>
        public string MatchStats {
            get {
                return ResourceManager.GetString("MatchStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Match Types.
        /// </summary>
        public string MatchTypes {
            get {
                return ResourceManager.GetString("MatchTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a (Mean) = +.
        /// </summary>
        public string Mean {
            get {
                return ResourceManager.GetString("Mean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Mot.
        /// </summary>
        public string Mot {
            get {
                return ResourceManager.GetString("Mot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Move Player To A Team.
        /// </summary>
        public string MovePlayerToATeam {
            get {
                return ResourceManager.GetString("MovePlayerToATeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Move Player To B Team.
        /// </summary>
        public string MovePlayerToBTeam {
            get {
                return ResourceManager.GetString("MovePlayerToBTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Name.
        /// </summary>
        public string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nat.
        /// </summary>
        public string Nat {
            get {
                return ResourceManager.GetString("Nat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nationality.
        /// </summary>
        public string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Next Player.
        /// </summary>
        public string NextPlayer {
            get {
                return ResourceManager.GetString("NextPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Non-PRO Users must paste the Training Regimes (Allenamento) page.
        /// </summary>
        public string NonPROUsersMustPasteTheTrainingRegimesAllenamentoPage {
            get {
                return ResourceManager.GetString("NonPROUsersMustPasteTheTrainingRegimesAllenamentoPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Normalized.
        /// </summary>
        public string Normalized {
            get {
                return ResourceManager.GetString("Normalized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Normalize Gains.
        /// </summary>
        public string NormalizeGains {
            get {
                return ResourceManager.GetString("NormalizeGains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Notes.
        /// </summary>
        public string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Notes from the Player&apos;s page.
        /// </summary>
        public string NotesFromThePlayerSPage {
            get {
                return ResourceManager.GetString("NotesFromThePlayerSPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a One.
        /// </summary>
        public string One {
            get {
                return ResourceManager.GetString("One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Open Players Profile Pages.
        /// </summary>
        public string OpenPlayersProfilePages {
            get {
                return ResourceManager.GetString("OpenPlayersProfilePages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Open Players Scout Pages.
        /// </summary>
        public string OpenPlayersScoutPages {
            get {
                return ResourceManager.GetString("OpenPlayersScoutPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Open Team Calendar Page.
        /// </summary>
        public string OpenTeamCalendarPage {
            get {
                return ResourceManager.GetString("OpenTeamCalendarPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Opposite Team.
        /// </summary>
        public string OppositeTeam {
            get {
                return ResourceManager.GetString("OppositeTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Options.
        /// </summary>
        public string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Other Options.
        /// </summary>
        public string OtherOptions {
            get {
                return ResourceManager.GetString("OtherOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Pac.
        /// </summary>
        public string Pac {
            get {
                return ResourceManager.GetString("Pac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Pace.
        /// </summary>
        public string Pace {
            get {
                return ResourceManager.GetString("Pace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Parameters.
        /// </summary>
        public string Parameters {
            get {
                return ResourceManager.GetString("Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Parse Scout Review for Hidden Data.
        /// </summary>
        public string ParseScoutReviewForHiddenData {
            get {
                return ResourceManager.GetString("ParseScoutReviewForHiddenData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Pas.
        /// </summary>
        public string Pas {
            get {
                return ResourceManager.GetString("Pas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Passing.
        /// </summary>
        public string Passing {
            get {
                return ResourceManager.GetString("Passing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Paste Calendar.
        /// </summary>
        public string PasteCalendar {
            get {
                return ResourceManager.GetString("PasteCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Paste from Clipboard.
        /// </summary>
        public string PasteFromClipboard {
            get {
                return ResourceManager.GetString("PasteFromClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Paste HTML.
        /// </summary>
        public string PasteHTML {
            get {
                return ResourceManager.GetString("PasteHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Paste Scout List.
        /// </summary>
        public string PasteScoutList {
            get {
                return ResourceManager.GetString("PasteScoutList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Paste Selected Match from File.
        /// </summary>
        public string PasteSelectedMatchFromFile {
            get {
                return ResourceManager.GetString("PasteSelectedMatchFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Paste Selected Match HTML.
        /// </summary>
        public string PasteSelectedMatchHTML {
            get {
                return ResourceManager.GetString("PasteSelectedMatchHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Paste Squad data from Excel Form.
        /// </summary>
        public string PasteSquadDataFromExcelForm {
            get {
                return ResourceManager.GetString("PasteSquadDataFromExcelForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Paste Squad Page from Clipboard.
        /// </summary>
        public string PasteSquadPageFromClipboard {
            get {
                return ResourceManager.GetString("PasteSquadPageFromClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Paste Trainers List.
        /// </summary>
        public string PasteTrainersList {
            get {
                return ResourceManager.GetString("PasteTrainersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Paste Training Page from Clipboard.
        /// </summary>
        public string PasteTrainingPageFromClipboard {
            get {
                return ResourceManager.GetString("PasteTrainingPageFromClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Performances.
        /// </summary>
        public string Performances {
            get {
                return ResourceManager.GetString("Performances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Phy.
        /// </summary>
        public string Phy {
            get {
                return ResourceManager.GetString("Phy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Phys.
        /// </summary>
        public string Phys {
            get {
                return ResourceManager.GetString("Phys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Physics skills potential.
        /// </summary>
        public string PhysicsSkillsPotential {
            get {
                return ResourceManager.GetString("PhysicsSkillsPotential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Physique.
        /// </summary>
        public string Physique {
            get {
                return ResourceManager.GetString("Physique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Player History.
        /// </summary>
        public string PlayerHistory {
            get {
                return ResourceManager.GetString("PlayerHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Player Info.
        /// </summary>
        public string PlayerInfo {
            get {
                return ResourceManager.GetString("PlayerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Player Infos.
        /// </summary>
        public string PlayerInfos {
            get {
                return ResourceManager.GetString("PlayerInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Players File Editor.
        /// </summary>
        public string PlayersFileEditor {
            get {
                return ResourceManager.GetString("PlayersFileEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Players Info.
        /// </summary>
        public string PlayersInfo {
            get {
                return ResourceManager.GetString("PlayersInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Player Skills.
        /// </summary>
        public string PlayerSkills {
            get {
                return ResourceManager.GetString("PlayerSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Players Statistics.
        /// </summary>
        public string PlayersStatistics {
            get {
                return ResourceManager.GetString("PlayersStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Player Training.
        /// </summary>
        public string PlayerTraining {
            get {
                return ResourceManager.GetString("PlayerTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Please download it from the tmrecorder web site and then select it from the Tools-&gt;Options panel..
        /// </summary>
        public string PleaseDownloadItFromTheTmrecorderWebSiteAndThenSelectItFromTheToolsOptionsPanel {
            get {
                return ResourceManager.GetString("PleaseDownloadItFromTheTmrecorderWebSiteAndThenSelectItFromTheToolsOptionsPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Please select a directory where to store team data.
        /// </summary>
        public string PleaseSelectADirectoryWhereToStoreTeamData {
            get {
                return ResourceManager.GetString("PleaseSelectADirectoryWhereToStoreTeamData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Please select in the table the match row you are pasting.
        /// </summary>
        public string PleaseSelectInTheTableTheMatchRowYouArePasting {
            get {
                return ResourceManager.GetString("PleaseSelectInTheTableTheMatchRowYouArePasting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ply.
        /// </summary>
        public string Ply {
            get {
                return ResourceManager.GetString("Ply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Pos.
        /// </summary>
        public string Pos {
            get {
                return ResourceManager.GetString("Pos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Positioning.
        /// </summary>
        public string Positioning {
            get {
                return ResourceManager.GetString("Positioning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Position of the player into the match field.
        /// </summary>
        public string PositionOfThePlayerIntoTheMatchField {
            get {
                return ResourceManager.GetString("PositionOfThePlayerIntoTheMatchField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Potential.
        /// </summary>
        public string Potential {
            get {
                return ResourceManager.GetString("Potential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Preferred Position.
        /// </summary>
        public string PreferredPosition {
            get {
                return ResourceManager.GetString("PreferredPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Pressing YES, all data of players that are no more in your team will be deleted.
        /// </summary>
        public string PressingYESAllDataOfPlayersThatAreNoMoreInYourTeamWillBeDeleted {
            get {
                return ResourceManager.GetString("PressingYESAllDataOfPlayersThatAreNoMoreInYourTeamWillBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Prev. Player.
        /// </summary>
        public string PrevPlayer {
            get {
                return ResourceManager.GetString("PrevPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Pro.
        /// </summary>
        public string Pro {
            get {
                return ResourceManager.GetString("Pro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Professionalism.
        /// </summary>
        public string Professionalism {
            get {
                return ResourceManager.GetString("Professionalism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Professionality.
        /// </summary>
        public string Professionality {
            get {
                return ResourceManager.GetString("Professionality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Program.
        /// </summary>
        public string Program {
            get {
                return ResourceManager.GetString("Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a PRO type selection.
        /// </summary>
        public string PROTypeSelection {
            get {
                return ResourceManager.GetString("PROTypeSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Psyc.
        /// </summary>
        public string Psyc {
            get {
                return ResourceManager.GetString("Psyc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 
        ///Real Delta Skills = +.
        /// </summary>
        public string RealDeltaSkills {
            get {
                return ResourceManager.GetString("RealDeltaSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a (Real Mean) = +.
        /// </summary>
        public string RealMean {
            get {
                return ResourceManager.GetString("RealMean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Reapply Trainings.
        /// </summary>
        public string ReapplyTrainings {
            get {
                return ResourceManager.GetString("ReapplyTrainings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Recalculate Players&apos; Scouts Mean Vote.
        /// </summary>
        public string RecalculatePlayersScoutsMeanVote {
            get {
                return ResourceManager.GetString("RecalculatePlayersScoutsMeanVote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Recalculate Players&apos; Statistics.
        /// </summary>
        public string RecalculatePlayersStatistics {
            get {
                return ResourceManager.GetString("RecalculatePlayersStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ref.
        /// </summary>
        public string Ref {
            get {
                return ResourceManager.GetString("Ref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Reload Players Match Stats.
        /// </summary>
        public string ReloadPlayersMatchStats {
            get {
                return ResourceManager.GetString("ReloadPlayersMatchStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Reload Squad Data from the selected directory?.
        /// </summary>
        public string ReloadSquadDataFromTheSelectedDirectory {
            get {
                return ResourceManager.GetString("ReloadSquadDataFromTheSelectedDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Remove data item.
        /// </summary>
        public string RemoveDataItem {
            get {
                return ResourceManager.GetString("RemoveDataItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Report Analysis.
        /// </summary>
        public string ReportAnalysis {
            get {
                return ResourceManager.GetString("ReportAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Report Analysis File:.
        /// </summary>
        public string ReportAnalysisFile {
            get {
                return ResourceManager.GetString("ReportAnalysisFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Report Analysis Filename.
        /// </summary>
        public string ReportAnalysisFilename {
            get {
                return ResourceManager.GetString("ReportAnalysisFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Res.
        /// </summary>
        public string Res {
            get {
                return ResourceManager.GetString("Res", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Reserves.
        /// </summary>
        public string Reserves {
            get {
                return ResourceManager.GetString("Reserves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Reserve Squad.
        /// </summary>
        public string ReserveSquad {
            get {
                return ResourceManager.GetString("ReserveSquad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Result.
        /// </summary>
        public string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Review.
        /// </summary>
        public string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Rou.
        /// </summary>
        public string Rou {
            get {
                return ResourceManager.GetString("Rou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Routine.
        /// </summary>
        public string Routine {
            get {
                return ResourceManager.GetString("Routine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Save.
        /// </summary>
        public string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Save As....
        /// </summary>
        public string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Save data before exit?.
        /// </summary>
        public string SaveDataBeforeExit {
            get {
                return ResourceManager.GetString("SaveDataBeforeExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Save matches data before exit?.
        /// </summary>
        public string SaveMatchesDataBeforeExit {
            get {
                return ResourceManager.GetString("SaveMatchesDataBeforeExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Save Team Data.
        /// </summary>
        public string SaveTeamData {
            get {
                return ResourceManager.GetString("SaveTeamData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Season.
        /// </summary>
        public string Season {
            get {
                return ResourceManager.GetString("Season", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select a Gain Set (Reply Yes) or use a default set (Reply No)?.
        /// </summary>
        public string SelectAGainSetReplyYesOrUseADefaultSetReplyNo {
            get {
                return ResourceManager.GetString("SelectAGainSetReplyYesOrUseADefaultSetReplyNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select the location where to save the gain file.
        /// </summary>
        public string SelectTheLocationWhereToSaveTheGainFile {
            get {
                return ResourceManager.GetString("SelectTheLocationWhereToSaveTheGainFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Senr.
        /// </summary>
        public string Senr {
            get {
                return ResourceManager.GetString("Senr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Set.
        /// </summary>
        public string Set {
            get {
                return ResourceManager.GetString("Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Set Pieces.
        /// </summary>
        public string SetPieces {
            get {
                return ResourceManager.GetString("SetPieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Show Match Actions List.
        /// </summary>
        public string ShowMatchActionsList {
            get {
                return ResourceManager.GetString("ShowMatchActionsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Show Matches Performarces on the Field.
        /// </summary>
        public string ShowMatchesPerformarcesOnTheField {
            get {
                return ResourceManager.GetString("ShowMatchesPerformarcesOnTheField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Show Position.
        /// </summary>
        public string ShowPosition {
            get {
                return ResourceManager.GetString("ShowPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Skills.
        /// </summary>
        public string Skills {
            get {
                return ResourceManager.GetString("Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sorry. The importing process has failed. If you clicked ok, the info of the error have .
        /// </summary>
        public string SorryTheImportingProcessHasFailedIfYouClickedOkTheInfoOfTheErrorHave {
            get {
                return ResourceManager.GetString("SorryTheImportingProcessHasFailedIfYouClickedOkTheInfoOfTheErrorHave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Squad.
        /// </summary>
        public string Squad {
            get {
                return ResourceManager.GetString("Squad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Squad Data Directory.
        /// </summary>
        public string SquadDataDirectory {
            get {
                return ResourceManager.GetString("SquadDataDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sta.
        /// </summary>
        public string Sta {
            get {
                return ResourceManager.GetString("Sta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Stamina.
        /// </summary>
        public string Stamina {
            get {
                return ResourceManager.GetString("Stamina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Str.
        /// </summary>
        public string Str {
            get {
                return ResourceManager.GetString("Str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Strength.
        /// </summary>
        public string Strength {
            get {
                return ResourceManager.GetString("Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tac.
        /// </summary>
        public string Tac {
            get {
                return ResourceManager.GetString("Tac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tact.
        /// </summary>
        public string Tact {
            get {
                return ResourceManager.GetString("Tact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tactical skills potential.
        /// </summary>
        public string TacticalSkillsPotential {
            get {
                return ResourceManager.GetString("TacticalSkillsPotential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tactics.
        /// </summary>
        public string Tactics {
            get {
                return ResourceManager.GetString("Tactics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tak.
        /// </summary>
        public string Tak {
            get {
                return ResourceManager.GetString("Tak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Takling.
        /// </summary>
        public string Takling {
            get {
                return ResourceManager.GetString("Takling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Team File Editor.
        /// </summary>
        public string TeamFileEditor {
            get {
                return ResourceManager.GetString("TeamFileEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Team Graphical Statistics.
        /// </summary>
        public string TeamGraphicalStatistics {
            get {
                return ResourceManager.GetString("TeamGraphicalStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Team Info.
        /// </summary>
        public string TeamInfo {
            get {
                return ResourceManager.GetString("TeamInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tec.
        /// </summary>
        public string Tec {
            get {
                return ResourceManager.GetString("Tec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tech.
        /// </summary>
        public string Tech {
            get {
                return ResourceManager.GetString("Tech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Technical skills potential.
        /// </summary>
        public string TechnicalSkillsPotential {
            get {
                return ResourceManager.GetString("TechnicalSkillsPotential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Technics.
        /// </summary>
        public string Technics {
            get {
                return ResourceManager.GetString("Technics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Technique.
        /// </summary>
        public string Technique {
            get {
                return ResourceManager.GetString("Technique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The Action Analysis Editor (ActionAnalysisEditor.exe) doesn&apos;t exist at the given path (.
        /// </summary>
        public string TheActionAnalysisEditorActionAnalysisEditorExeDoesnTExistAtTheGivenPath {
            get {
                return ResourceManager.GetString("TheActionAnalysisEditorActionAnalysisEditorExeDoesnTExistAtTheGivenPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The Action analysis file does not exists. 
        ///.
        /// </summary>
        public string TheActionAnalysisFileDoesNotExists {
            get {
                return ResourceManager.GetString("TheActionAnalysisFileDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The ASI to TI application (ASI2TI.exe) doesn&apos;t exist at the given path (.
        /// </summary>
        public string TheASIToTIApplicationASI2TIExeDoesnTExistAtTheGivenPath {
            get {
                return ResourceManager.GetString("TheASIToTIApplicationASI2TIExeDoesnTExistAtTheGivenPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The clipboard doesn&apos;t contains Excel Squad Form data.
        /// </summary>
        public string TheClipboardDoesnTContainsExcelSquadFormData {
            get {
                return ResourceManager.GetString("TheClipboardDoesnTContainsExcelSquadFormData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The clipboard doesn&apos;t contain Squad, Training or Match data
        ///.
        /// </summary>
        public string TheClipboardDoesnTContainSquadTrainingOrMatchData {
            get {
                return ResourceManager.GetString("TheClipboardDoesnTContainSquadTrainingOrMatchData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The content of what you pasted is not the one expected.
        /// </summary>
        public string TheContentOfWhatYouPastedIsNotTheOneExpected {
            get {
                return ResourceManager.GetString("TheContentOfWhatYouPastedIsNotTheOneExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The file .
        /// </summary>
        public string TheFile {
            get {
                return ResourceManager.GetString("TheFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The information for this match are not complete: the nick of your and opposite team have not been saved. Do you want to set yourself the nick?.
        /// </summary>
        public string TheInformationForThisMatchAreNotCompleteTheNickOfYourAndOppositeTeamHaveNotBeenSavedDoYouWantToSetYourselfTheNick {
            get {
                return ResourceManager.GetString("TheInformationForThisMatchAreNotCompleteTheNickOfYourAndOppositeTeamHaveNotBeenSa" +
                        "vedDoYouWantToSetYourselfTheNick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The match has not been downloaded from Trophymanager.
        /// </summary>
        public string TheMatchHasNotBeenDownloadedFromTrophymanager {
            get {
                return ResourceManager.GetString("TheMatchHasNotBeenDownloadedFromTrophymanager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The Player File Editor (PlayerFileEditor.exe) doesn&apos;t exist at the given path (.
        /// </summary>
        public string ThePlayerFileEditorPlayerFileEditorExeDoesnTExistAtTheGivenPath {
            get {
                return ResourceManager.GetString("ThePlayerFileEditorPlayerFileEditorExeDoesnTExistAtTheGivenPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a There is already a training data set in the same week of the one you are adding!
        ///.
        /// </summary>
        public string ThereIsAlreadyATrainingDataSetInTheSameWeekOfTheOneYouAreAdding {
            get {
                return ResourceManager.GetString("ThereIsAlreadyATrainingDataSetInTheSameWeekOfTheOneYouAreAdding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a There must be at least a squad data set after or in the same date of a training session.
        ///.
        /// </summary>
        public string ThereMustBeAtLeastASquadDataSetAfterOrInTheSameDateOfATrainingSession {
            get {
                return ResourceManager.GetString("ThereMustBeAtLeastASquadDataSetAfterOrInTheSameDateOfATrainingSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The Team File Editor (TeamFileEditor.exe) doesn&apos;t exist at the given path (.
        /// </summary>
        public string TheTeamFileEditorTeamFileEditorExeDoesnTExistAtTheGivenPath {
            get {
                return ResourceManager.GetString("TheTeamFileEditorTeamFileEditorExeDoesnTExistAtTheGivenPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The TMR Browser (TMRBrowser.exe) doesn&apos;t exist at the given path (.
        /// </summary>
        public string TheTMRBrowserTMRBrowserExeDoesnTExistAtTheGivenPath {
            get {
                return ResourceManager.GetString("TheTMRBrowserTMRBrowserExeDoesnTExistAtTheGivenPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The Transfer Manager (TransferManager.exe) doesn&apos;t exist at the given path (.
        /// </summary>
        public string TheTransferManagerTransferManagerExeDoesnTExistAtTheGivenPath {
            get {
                return ResourceManager.GetString("TheTransferManagerTransferManagerExeDoesnTExistAtTheGivenPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The weighted vote of the scouts and youth development, based on the ability of scouts on measuring youth and senior and their development.
        /// </summary>
        public string TheWeightedVoteOfTheScoutsAndYouthDevelopmentBasedOnTheAbilityOfSc {
            get {
                return ResourceManager.GetString("TheWeightedVoteOfTheScoutsAndYouthDevelopmentBasedOnTheAbilityOfSc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a This operation has not been implemented.
        /// </summary>
        public string ThisOperationHasNotBeenImplemented {
            get {
                return ResourceManager.GetString("ThisOperationHasNotBeenImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a This option is useful when you mount TmRecorder in a movable disk whose letter ma.
        /// </summary>
        public string ThisOptionIsUsefulWhenYouMountTmRecorderInAMovableDiskWhoseLetterMa {
            get {
                return ResourceManager.GetString("ThisOptionIsUsefulWhenYouMountTmRecorderInAMovableDiskWhoseLetterMa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Thr.
        /// </summary>
        public string Thr {
            get {
                return ResourceManager.GetString("Thr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tir.
        /// </summary>
        public string Tir {
            get {
                return ResourceManager.GetString("Tir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a TM Recorder - Load Gain Set.
        /// </summary>
        public string TMRecorderLoadGainSet {
            get {
                return ResourceManager.GetString("TMRecorderLoadGainSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 
        ///TM Recorder Statistics:
        ///Delta Skills = +.
        /// </summary>
        public string TMRecorderStatisticsDeltaSkills {
            get {
                return ResourceManager.GetString("TMRecorderStatisticsDeltaSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tools.
        /// </summary>
        public string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a toolStripContainer1.
        /// </summary>
        public string ToolStripContainer1 {
            get {
                return ResourceManager.GetString("ToolStripContainer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a (Total Mean) = +.
        /// </summary>
        public string TotalMean {
            get {
                return ResourceManager.GetString("TotalMean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Total Team TI = .
        /// </summary>
        public string TotalTeamTI {
            get {
                return ResourceManager.GetString("TotalTeamTI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a To use this menu item, you must copy the content of the page that opens when you
        ///.
        /// </summary>
        public string ToUseThisMenuItemYouMustCopyTheContentOfThePageThatOpensWhenYou {
            get {
                return ResourceManager.GetString("ToUseThisMenuItemYouMustCopyTheContentOfThePageThatOpensWhenYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Trading Form.
        /// </summary>
        public string TradingForm {
            get {
                return ResourceManager.GetString("TradingForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Trading Info.
        /// </summary>
        public string TradingInfo {
            get {
                return ResourceManager.GetString("TradingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Trainer.
        /// </summary>
        public string Trainer {
            get {
                return ResourceManager.GetString("Trainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Trainers.
        /// </summary>
        public string Trainers {
            get {
                return ResourceManager.GetString("Trainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Trainers Evaluation Form.
        /// </summary>
        public string TrainersEvaluationForm {
            get {
                return ResourceManager.GetString("TrainersEvaluationForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Training.
        /// </summary>
        public string Training {
            get {
                return ResourceManager.GetString("Training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Training Load.
        /// </summary>
        public string TrainingLoad {
            get {
                return ResourceManager.GetString("TrainingLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Training Paste error.
        /// </summary>
        public string TrainingPasteError {
            get {
                return ResourceManager.GetString("TrainingPasteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Training &amp; Potential.
        /// </summary>
        public string TrainingPotential {
            get {
                return ResourceManager.GetString("TrainingPotential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Training Program.
        /// </summary>
        public string TrainingProgram {
            get {
                return ResourceManager.GetString("TrainingProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Transfer Manager.
        /// </summary>
        public string TransferManager {
            get {
                return ResourceManager.GetString("TransferManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Trophy Manager Report:
        ///Light Green Arrows = .
        /// </summary>
        public string TrophyManagerReportLightGreenArrows {
            get {
                return ResourceManager.GetString("TrophyManagerReportLightGreenArrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Trophy Manager Report: 
        ///still not available for this week
        ///
        ///.
        /// </summary>
        public string TrophyManagerReportStillNotAvailableForThisWeek {
            get {
                return ResourceManager.GetString("TrophyManagerReportStillNotAvailableForThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Trophy Manager Statistics:
        ///Delta Skills = +.
        /// </summary>
        public string TrophyManagerStatisticsDeltaSkills {
            get {
                return ResourceManager.GetString("TrophyManagerStatisticsDeltaSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Type.
        /// </summary>
        public string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Type here the match types for your nation separated by comma and no space, in the following order: League match, Cup match, Friendly match, Friendly League Match, International Cup matches. Examples:
        ///England: L,C,F,FL,CC
        ///Italy: Ca,Co,Am,LA,UC
        ///Note: Modification of this field is necessary only if it is required from this application when you paste the match list..
        /// </summary>
        public string TypeHereTheMatchTypesForYourNationSeparated {
            get {
                return ResourceManager.GetString("TypeHereTheMatchTypesForYourNationSeparated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a User Type.
        /// </summary>
        public string UserType {
            get {
                return ResourceManager.GetString("UserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Use the startup disk for all paths.
        /// </summary>
        public string UseTheStartupDiskForAllPaths {
            get {
                return ResourceManager.GetString("UseTheStartupDiskForAllPaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Use TMR Browser instead of the default browser.
        /// </summary>
        public string UseTMRBrowserInsteadOfTheDefaultBrowser {
            get {
                return ResourceManager.GetString("UseTMRBrowserInsteadOfTheDefaultBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Vote.
        /// </summary>
        public string Vote {
            get {
                return ResourceManager.GetString("Vote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Votes.
        /// </summary>
        public string Votes {
            get {
                return ResourceManager.GetString("Votes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Wage.
        /// </summary>
        public string Wage {
            get {
                return ResourceManager.GetString("Wage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 
        ///Warning: TEMPORARY!!.
        /// </summary>
        public string WarningTEMPORARY {
            get {
                return ResourceManager.GetString("WarningTEMPORARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Week.
        /// </summary>
        public string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Weeks Data.
        /// </summary>
        public string WeeksData {
            get {
                return ResourceManager.GetString("WeeksData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a What to do here?.
        /// </summary>
        public string WhatToDoHere {
            get {
                return ResourceManager.GetString("WhatToDoHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a  will be definively removed. Continue?.
        /// </summary>
        public string WillBeDefinivelyRemovedContinue {
            get {
                return ResourceManager.GetString("WillBeDefinivelyRemovedContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Win.
        /// </summary>
        public string Win {
            get {
                return ResourceManager.GetString("Win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Wor.
        /// </summary>
        public string Wor {
            get {
                return ResourceManager.GetString("Wor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Work Rate.
        /// </summary>
        public string WorkRate {
            get {
                return ResourceManager.GetString("WorkRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a You cannot paste a running training. You must wait the end of the training!.
        /// </summary>
        public string YouCannotPasteARunningTrainingYouMustWaitTheEndOfTheTraining {
            get {
                return ResourceManager.GetString("YouCannotPasteARunningTrainingYouMustWaitTheEndOfTheTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a You have to import a least one Squad.htm file before importing your players.
        /// </summary>
        public string YouHaveToImportALeastOneSquadHtmFileBeforeImportingYourPlayers {
            get {
                return ResourceManager.GetString("YouHaveToImportALeastOneSquadHtmFileBeforeImportingYourPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a You have to paste the trainers (Options-&gt;Trainers) page before to enter a new training session.
        /// </summary>
        public string YouHaveToPasteTheTrainersOptionsTrainersPageBeforeToEnterANewTrainingSession {
            get {
                return ResourceManager.GetString("YouHaveToPasteTheTrainersOptionsTrainersPageBeforeToEnterANewTrainingSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a You must select a date in which you pasted a training page.
        /// </summary>
        public string YouMustSelectADateInWhichYouPastedATrainingPage {
            get {
                return ResourceManager.GetString("YouMustSelectADateInWhichYouPastedATrainingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Your Team.
        /// </summary>
        public string YourTeam {
            get {
                return ResourceManager.GetString("YourTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Your Teams Data.
        /// </summary>
        public string YourTeamsData {
            get {
                return ResourceManager.GetString("YourTeamsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Youth.
        /// </summary>
        public string Youth {
            get {
                return ResourceManager.GetString("Youth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Youth Development.
        /// </summary>
        public string YouthDevelopment {
            get {
                return ResourceManager.GetString("YouthDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///  Returns true if the current language is the default language.
        /// </summary>
        public bool IsDefault {
            get {
                return true;
            }
        }
        
        /// <summary>
        ///  Returns a System.String that represents the current System.Object.
        /// </summary>
        public override string ToString() {
            return Culture.EnglishName;
        }
    }
}
