//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMFinanceCalculator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fast Food / Bar Level")]
        public string BarLabel {
            get {
                return ((string)(this["BarLabel"]));
            }
            set {
                this["BarLabel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Structures Level")]
        public string StructuresLabel {
            get {
                return ((string)(this["StructuresLabel"]));
            }
            set {
                this["StructuresLabel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("optionsToolStripMenuItem")]
        public string OptionsLabel {
            get {
                return ((string)(this["OptionsLabel"]));
            }
            set {
                this["OptionsLabel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sausages Level")]
        public string SausageLabel {
            get {
                return ((string)(this["SausageLabel"]));
            }
            set {
                this["SausageLabel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Restaurant Level")]
        public string RestaurantLabel {
            get {
                return ((string)(this["RestaurantLabel"]));
            }
            set {
                this["RestaurantLabel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Vip Level")]
        public string VipLabel {
            get {
                return ((string)(this["VipLabel"]));
            }
            set {
                this["VipLabel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Division")]
        public string DivisionLabel {
            get {
                return ((string)(this["DivisionLabel"]));
            }
            set {
                this["DivisionLabel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("League Position")]
        public string LeaguePosLabel {
            get {
                return ((string)(this["LeaguePosLabel"]));
            }
            set {
                this["LeaguePosLabel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Avoid Relegation")]
        public string LeaguePos1Label {
            get {
                return ((string)(this["LeaguePos1Label"]));
            }
            set {
                this["LeaguePos1Label"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Top 12")]
        public string LeaguePos2Label {
            get {
                return ((string)(this["LeaguePos2Label"]));
            }
            set {
                this["LeaguePos2Label"] = value;
            }
        }
    }
}
